module: default
version: v1
runtime: go
api_version: go1
threadsafe: true

instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms
  max_concurrent_requests: 50

handlers:
- url: .*/assets/
  static_dir: assets
  application_readable: true

- url: .*/templates/
  static_dir: templates
  application_readable: true

- url: /.*
  script: _go_app
